const palette = {
  performance: {
    accentColor: "#ffd60a",
    iconBackground: "rgba(255, 214, 10, 0.18)",
  },
  strength: {
    accentColor: "#bf5af2",
    iconBackground: "rgba(191, 90, 242, 0.18)",
  },
  mindful: {
    accentColor: "#a87ffb",
    iconBackground: "rgba(168, 127, 251, 0.18)",
  },
  aqua: {
    accentColor: "#64d2ff",
    iconBackground: "rgba(100, 210, 255, 0.18)",
  },
  outdoor: {
    accentColor: "#30d158",
    iconBackground: "rgba(48, 209, 88, 0.18)",
  },
  intense: {
    accentColor: "#ff3b30",
    iconBackground: "rgba(255, 59, 48, 0.18)",
  },
  play: {
    accentColor: "#ff9f0a",
    iconBackground: "rgba(255, 159, 10, 0.18)",
  },
  neutral: {
    accentColor: "#8e8e93",
    iconBackground: "rgba(142, 142, 147, 0.18)",
  },
};

const defaultType = {
  label: "Workout",
  icon: "💪",
  iconSymbol: "bolt.circle.fill",
  ...palette.outdoor,
};

const workoutTypes = {
  HKWorkoutActivityTypeAmericanFootball: {
    label: "American Football",
    icon: "🏈",
    iconSymbol: "sportscourt.fill",
    ...palette.play,
  },
  HKWorkoutActivityTypeArchery: {
    label: "Archery",
    icon: "🏹",
    iconSymbol: "scope",
    ...palette.play,
  },
  HKWorkoutActivityTypeAustralianFootball: {
    label: "Australian Football",
    icon: "🏉",
    iconSymbol: "sportscourt.fill",
    ...palette.play,
  },
  HKWorkoutActivityTypeBadminton: {
    label: "Badminton",
    icon: "🏸",
    iconSymbol: "sportscourt",
    ...palette.performance,
  },
  HKWorkoutActivityTypeBarre: {
    label: "Barre",
    icon: "🩰",
    iconSymbol: "sparkles",
    ...palette.mindful,
  },
  HKWorkoutActivityTypeBaseball: {
    label: "Baseball",
    icon: "⚾",
    iconSymbol: "sportscourt.fill",
    ...palette.play,
  },
  HKWorkoutActivityTypeBasketball: {
    label: "Basketball",
    icon: "🏀",
    iconSymbol: "sportscourt.fill",
    ...palette.play,
  },
  HKWorkoutActivityTypeBowling: {
    label: "Bowling",
    icon: "🎳",
    iconSymbol: "sportscourt",
    ...palette.play,
  },
  HKWorkoutActivityTypeBoxing: {
    label: "Boxing",
    icon: "🥊",
    iconSymbol: "waveform.path.ecg",
    ...palette.intense,
  },
  HKWorkoutActivityTypeCardioDance: {
    label: "Cardio Dance",
    icon: "💃",
    iconSymbol: "music.note",
    ...palette.performance,
  },
  HKWorkoutActivityTypeClimbing: {
    label: "Climbing",
    icon: "🧗",
    iconSymbol: "flag.circle.fill",
    ...palette.performance,
  },
  HKWorkoutActivityTypeCooldown: {
    label: "Cooldown",
    icon: "🧊",
    iconSymbol: "snow",
    ...palette.neutral,
  },
  HKWorkoutActivityTypeCoreTraining: {
    label: "Core Training",
    icon: "🧘",
    iconSymbol: "leaf.arrow.circlepath",
    ...palette.strength,
  },
  HKWorkoutActivityTypeCricket: {
    label: "Cricket",
    icon: "🏏",
    iconSymbol: "sportscourt",
    ...palette.play,
  },
  HKWorkoutActivityTypeCrossCountrySkiing: {
    label: "Cross-Country Skiing",
    icon: "🎿",
    iconSymbol: "snow",
    ...palette.performance,
  },
  HKWorkoutActivityTypeCrossTraining: {
    label: "Cross Training",
    icon: "🏋️",
    iconSymbol: "bolt.circle.fill",
    ...palette.strength,
  },
  HKWorkoutActivityTypeCurling: {
    label: "Curling",
    icon: "🥌",
    iconSymbol: "snow",
    ...palette.aqua,
  },
  HKWorkoutActivityTypeCycling: {
    label: "Cycling",
    icon: "🚴",
    iconSymbol: "wind",
    ...palette.performance,
  },
  HKWorkoutActivityTypeDance: {
    label: "Dance",
    icon: "🕺",
    iconSymbol: "music.note",
    ...palette.performance,
  },
  HKWorkoutActivityTypeDanceInspiredTraining: {
    label: "Dance Inspired",
    icon: "🩰",
    iconSymbol: "sparkles",
    ...palette.performance,
  },
  HKWorkoutActivityTypeDiscSports: {
    label: "Disc Sports",
    icon: "🥏",
    iconSymbol: "sportscourt",
    ...palette.play,
  },
  HKWorkoutActivityTypeDownhillSkiing: {
    label: "Downhill Skiing",
    icon: "⛷️",
    iconSymbol: "snow",
    ...palette.performance,
  },
  HKWorkoutActivityTypeElliptical: {
    label: "Elliptical",
    icon: "🚴",
    iconSymbol: "wind",
    ...palette.performance,
  },
  HKWorkoutActivityTypeEquestrianSports: {
    label: "Equestrian",
    icon: "🐎",
    iconSymbol: "hare.fill",
    ...palette.play,
  },
  HKWorkoutActivityTypeFencing: {
    label: "Fencing",
    icon: "🤺",
    iconSymbol: "scope",
    ...palette.play,
  },
  HKWorkoutActivityTypeFishing: {
    label: "Fishing",
    icon: "🎣",
    iconSymbol: "drop.triangle.fill",
    ...palette.outdoor,
  },
  HKWorkoutActivityTypeFitnessGaming: {
    label: "Fitness Gaming",
    icon: "🎮",
    iconSymbol: "gamecontroller.fill",
    ...palette.outdoor,
  },
  HKWorkoutActivityTypeFlexibility: {
    label: "Flexibility",
    icon: "🤸",
    iconSymbol: "hare.fill",
    ...palette.mindful,
  },
  HKWorkoutActivityTypeFunctionalStrengthTraining: {
    label: "Functional Strength",
    icon: "🏋️",
    iconSymbol: "bolt.circle.fill",
    ...palette.strength,
  },
  HKWorkoutActivityTypeGolf: {
    label: "Golf",
    icon: "⛳",
    iconSymbol: "flag.circle.fill",
    ...palette.outdoor,
  },
  HKWorkoutActivityTypeGymnastics: {
    label: "Gymnastics",
    icon: "🤸",
    iconSymbol: "hare.fill",
    ...palette.performance,
  },
  HKWorkoutActivityTypeHandCycling: {
    label: "Hand Cycling",
    icon: "♿",
    iconSymbol: "person.circle.fill",
    ...palette.performance,
  },
  HKWorkoutActivityTypeHandball: {
    label: "Handball",
    icon: "🤾",
    iconSymbol: "sportscourt.fill",
    ...palette.intense,
  },
  HKWorkoutActivityTypeHighIntensityIntervalTraining: {
    label: "HIIT",
    icon: "⚡",
    iconSymbol: "bolt.fill",
    ...palette.intense,
  },
  HKWorkoutActivityTypeHiking: {
    label: "Hiking",
    icon: "🥾",
    iconSymbol: "flag.circle.fill",
    ...palette.outdoor,
  },
  HKWorkoutActivityTypeHockey: {
    label: "Hockey",
    icon: "🏒",
    iconSymbol: "sportscourt",
    ...palette.aqua,
  },
  HKWorkoutActivityTypeHunting: {
    label: "Hunting",
    icon: "🎯",
    iconSymbol: "scope",
    ...palette.outdoor,
  },
  HKWorkoutActivityTypeIceHockey: {
    label: "Ice Hockey",
    icon: "🏒",
    iconSymbol: "sportscourt",
    ...palette.aqua,
  },
  HKWorkoutActivityTypeJumpRope: {
    label: "Jump Rope",
    icon: "🪢",
    iconSymbol: "leaf.arrow.circlepath",
    ...palette.intense,
  },
  HKWorkoutActivityTypeKickboxing: {
    label: "Kickboxing",
    icon: "🥊",
    iconSymbol: "waveform.path.ecg",
    ...palette.intense,
  },
  HKWorkoutActivityTypeLacrosse: {
    label: "Lacrosse",
    icon: "🥍",
    iconSymbol: "sportscourt",
    ...palette.play,
  },
  HKWorkoutActivityTypeMartialArts: {
    label: "Martial Arts",
    icon: "🥋",
    iconSymbol: "bolt.circle.fill",
    ...palette.intense,
  },
  HKWorkoutActivityTypeMindAndBody: {
    label: "Mind & Body",
    icon: "🧘",
    iconSymbol: "leaf.arrow.circlepath",
    ...palette.mindful,
  },
  HKWorkoutActivityTypeMixedCardio: {
    label: "Mixed Cardio",
    icon: "❤️",
    iconSymbol: "heart.fill",
    ...palette.performance,
  },
  HKWorkoutActivityTypeMixedMetabolicCardioTraining: {
    label: "Metabolic Cardio",
    icon: "🔥",
    iconSymbol: "flame.fill",
    ...palette.intense,
  },
  HKWorkoutActivityTypeOther: {
    label: "Other",
    icon: "⭐",
    iconSymbol: "sparkles",
    ...palette.neutral,
  },
  HKWorkoutActivityTypePaddleSports: {
    label: "Paddle Sports",
    icon: "🛶",
    iconSymbol: "drop.triangle.fill",
    ...palette.aqua,
  },
  HKWorkoutActivityTypePickleball: {
    label: "Pickleball",
    icon: "🥒",
    iconSymbol: "leaf.arrow.circlepath",
    ...palette.play,
  },
  HKWorkoutActivityTypePilates: {
    label: "Pilates",
    icon: "🧘",
    iconSymbol: "leaf.arrow.circlepath",
    ...palette.mindful,
  },
  HKWorkoutActivityTypePlay: {
    label: "Play",
    icon: "🎲",
    iconSymbol: "gamecontroller.fill",
    ...palette.play,
  },
  HKWorkoutActivityTypePreparationAndRecovery: {
    label: "Recovery",
    icon: "🧊",
    iconSymbol: "snow",
    ...palette.neutral,
  },
  HKWorkoutActivityTypeRacquetball: {
    label: "Racquetball",
    icon: "🎾",
    iconSymbol: "sportscourt",
    ...palette.play,
  },
  HKWorkoutActivityTypeRowing: {
    label: "Rowing",
    icon: "🚣",
    iconSymbol: "drop.triangle.fill",
    ...palette.aqua,
  },
  HKWorkoutActivityTypeRugby: {
    label: "Rugby",
    icon: "🏉",
    iconSymbol: "sportscourt.fill",
    ...palette.play,
  },
  HKWorkoutActivityTypeRunning: {
    label: "Running",
    icon: "🏃",
    iconSymbol: "hare.fill",
    ...palette.performance,
  },
  HKWorkoutActivityTypeSailing: {
    label: "Sailing",
    icon: "⛵",
    iconSymbol: "wind",
    ...palette.aqua,
  },
  HKWorkoutActivityTypeSkatingSports: {
    label: "Skating",
    icon: "⛸️",
    iconSymbol: "snow",
    ...palette.performance,
  },
  HKWorkoutActivityTypeSnowSports: {
    label: "Snow Sports",
    icon: "🏂",
    iconSymbol: "snow",
    ...palette.performance,
  },
  HKWorkoutActivityTypeSnowboarding: {
    label: "Snowboarding",
    icon: "🏂",
    iconSymbol: "snow",
    ...palette.performance,
  },
  HKWorkoutActivityTypeSoccer: {
    label: "Soccer",
    icon: "⚽",
    iconSymbol: "sportscourt.fill",
    ...palette.outdoor,
  },
  HKWorkoutActivityTypeSoftball: {
    label: "Softball",
    icon: "🥎",
    iconSymbol: "sportscourt",
    ...palette.play,
  },
  HKWorkoutActivityTypeSquash: {
    label: "Squash",
    icon: "🎾",
    iconSymbol: "sportscourt",
    ...palette.play,
  },
  HKWorkoutActivityTypeStairClimbing: {
    label: "Stair Climbing",
    icon: "🧗",
    iconSymbol: "flag.circle.fill",
    ...palette.performance,
  },
  HKWorkoutActivityTypeStairs: {
    label: "Stairs",
    icon: "🧗",
    iconSymbol: "flag.circle.fill",
    ...palette.performance,
  },
  HKWorkoutActivityTypeStepTraining: {
    label: "Step Training",
    icon: "🚶",
    iconSymbol: "tortoise.fill",
    ...palette.outdoor,
  },
  HKWorkoutActivityTypeStrengthTraining: {
    label: "Strength Training",
    icon: "🏋️",
    iconSymbol: "bolt.circle.fill",
    ...palette.strength,
  },
  HKWorkoutActivityTypeStretching: {
    label: "Stretching",
    icon: "🧎",
    iconSymbol: "leaf.arrow.circlepath",
    ...palette.mindful,
  },
  HKWorkoutActivityTypeSurfingSports: {
    label: "Surfing",
    icon: "🏄",
    iconSymbol: "drop.triangle.fill",
    ...palette.aqua,
  },
  HKWorkoutActivityTypeSwimming: {
    label: "Swimming",
    icon: "🏊",
    iconSymbol: "drop.triangle.fill",
    ...palette.aqua,
  },
  HKWorkoutActivityTypeTableTennis: {
    label: "Table Tennis",
    icon: "🏓",
    iconSymbol: "sportscourt",
    ...palette.play,
  },
  HKWorkoutActivityTypeTaiChi: {
    label: "Tai Chi",
    icon: "🧘",
    iconSymbol: "leaf.arrow.circlepath",
    ...palette.mindful,
  },
  HKWorkoutActivityTypeTennis: {
    label: "Tennis",
    icon: "🎾",
    iconSymbol: "sportscourt",
    ...palette.play,
  },
  HKWorkoutActivityTypeTrackAndField: {
    label: "Track & Field",
    icon: "🏃",
    iconSymbol: "hare.fill",
    ...palette.performance,
  },
  HKWorkoutActivityTypeTraditionalStrengthTraining: {
    label: "Traditional Strength",
    icon: "🏋️",
    iconSymbol: "bolt.circle.fill",
    ...palette.strength,
  },
  HKWorkoutActivityTypeUnderwaterDiving: {
    label: "Diving",
    icon: "🤿",
    iconSymbol: "drop.triangle.fill",
    ...palette.aqua,
  },
  HKWorkoutActivityTypeVolleyball: {
    label: "Volleyball",
    icon: "🏐",
    iconSymbol: "sportscourt",
    ...palette.play,
  },
  HKWorkoutActivityTypeWalking: {
    label: "Walking",
    icon: "🚶",
    iconSymbol: "tortoise.fill",
    ...palette.outdoor,
  },
  HKWorkoutActivityTypeWaterFitness: {
    label: "Water Fitness",
    icon: "🤽",
    iconSymbol: "drop.triangle.fill",
    ...palette.aqua,
  },
  HKWorkoutActivityTypeWaterPolo: {
    label: "Water Polo",
    icon: "🤽",
    iconSymbol: "drop.triangle.fill",
    ...palette.aqua,
  },
  HKWorkoutActivityTypeWaterSports: {
    label: "Water Sports",
    icon: "🛶",
    iconSymbol: "drop.triangle.fill",
    ...palette.aqua,
  },
  HKWorkoutActivityTypeWheelchairRunPace: {
    label: "Wheelchair Run",
    icon: "♿",
    iconSymbol: "person.circle.fill",
    ...palette.performance,
  },
  HKWorkoutActivityTypeWheelchairWalkPace: {
    label: "Wheelchair Walk",
    icon: "♿",
    iconSymbol: "person.circle.fill",
    ...palette.outdoor,
  },
  HKWorkoutActivityTypeWrestling: {
    label: "Wrestling",
    icon: "🤼",
    iconSymbol: "bolt.circle.fill",
    ...palette.intense,
  },
  HKWorkoutActivityTypeYoga: {
    label: "Yoga",
    icon: "🧘",
    iconSymbol: "leaf.arrow.circlepath",
    ...palette.mindful,
  },
  HKWorkoutActivityTypeMindfulness: {
    label: "Mindfulness",
    icon: "🧘",
    iconSymbol: "leaf.arrow.circlepath",
    ...palette.mindful,
  },
};

module.exports = { workoutTypes, defaultType };
